"use client";
import {useEffect,useState} from "react";
import {Clock,Save} from "lucide-react";
import {Checkbox} from "@/components/ui/checkbox";
import {DAY_NAMES,timeLabel,type DayHours} from "@/lib/booking";
export default function HoursEditor(){const [hours,setHours]=useState<DayHours[]>([]),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState(""),[notice,setNotice]=useState("");
 async function load(){setLoading(true);setError("");try{const r=await fetch("/api/hours",{cache:"no-store"}),j:any=await r.json();if(!r.ok)throw Error(j.error);setHours(j.hours)}catch(e){setError(e instanceof Error?e.message:"Não foi possível carregar os horários.")}finally{setLoading(false)}}
 useEffect(()=>{load()},[]);
 function edit(day:number,key:"enabled"|"opens"|"closes",value:boolean|number){setHours(v=>v.map(h=>h.weekday===day?{...h,[key]:value}:h));setNotice("")}
 function minute(value:string){const [h,m]=value.split(":").map(Number);return h*60+m}
 async function save(e:React.FormEvent){e.preventDefault();setError("");setNotice("");if(hours.some(h=>h.closes<=h.opens||h.opens%30||h.closes%30)){setError("Use horários de meia em meia hora e fechamento depois da abertura.");return}setSaving(true);try{const r=await fetch("/api/hours",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({hours})}),j:any=await r.json();if(!r.ok)throw Error(j.error);setHours(j.hours);setNotice("Horários salvos. A agenda dos clientes já segue os novos dias e horários.")}catch(e){setError(e instanceof Error?e.message:"Não foi possível salvar os horários.")}finally{setSaving(false)}}
 return <section id="horarios" className="service-editor"><h3><Clock size={20}/>Horários de atendimento</h3><p className="muted">Escolha os dias abertos e os horários de cada dia. Use intervalos de 30 minutos. Reservas já feitas continuam válidas.</p>{loading?<p role="status">Carregando horários…</p>:hours.length?<form onSubmit={save}><fieldset disabled={saving} className="hours-fields">{[1,2,3,4,5,6,0].map(day=>{const h=hours.find(h=>h.weekday===day)!;return <div className={`hours-row ${h.enabled?"":"day-closed"}`} key={day}><div className="hours-day"><Checkbox id={`day-${day}`} checked={h.enabled} onCheckedChange={v=>edit(day,"enabled",v===true)}/><label htmlFor={`day-${day}`}>{DAY_NAMES[day]}<small>{h.enabled?"Aberto":"Fechado"}</small></label></div><label>Abertura<input aria-label={`Abertura de ${DAY_NAMES[day]}`} type="time" min="00:00" max="23:00" step={1800} value={timeLabel(h.opens)} disabled={!h.enabled} onChange={e=>edit(day,"opens",minute(e.target.value))} required={h.enabled}/></label><label>Fechamento<input aria-label={`Fechamento de ${DAY_NAMES[day]}`} type="time" min="00:30" max="23:30" step={1800} value={timeLabel(h.closes)} disabled={!h.enabled} onChange={e=>edit(day,"closes",minute(e.target.value))} required={h.enabled}/></label></div>})}<button className="primary" type="submit"><Save size={18}/>{saving?"Salvando…":"Salvar horários"}</button></fieldset></form>:<button className="primary" onClick={load}>Tentar novamente</button>}{error&&<p role="alert" className="error">{error}</p>}{notice&&<p role="status" className="admin-notice">{notice}</p>}</section>
}
