"use client";
import {useEffect,useState} from "react";
import {Scissors,Save,Plus} from "lucide-react";
import {NativeSelect,NativeSelectOption} from "@/components/ui/native-select";
import type {Service} from "@/lib/services";
type Draft={id:string;name:string;price:string;duration:number};
const drafts=(services:Service[]):Draft[]=>services.map(s=>({id:s.id,name:s.name,price:(s.priceCents/100).toFixed(2).replace(".",","),duration:s.duration}));
export default function ServiceEditor(){
 const [items,setItems]=useState<Draft[]>([]),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState(""),[notice,setNotice]=useState("");
 async function load(){setLoading(true);setError("");try{const r=await fetch("/api/services",{cache:"no-store"}),j:any=await r.json();if(!r.ok)throw Error(j.error);setItems(drafts(j.services))}catch(e){setError(e instanceof Error?e.message:"Não foi possível carregar os serviços.")}finally{setLoading(false)}}
 useEffect(()=>{load()},[]);
 function edit(id:string,key:"name"|"price"|"duration",value:string|number){setItems(items=>items.map(s=>s.id===id?{...s,[key]:value}:s));setNotice("")}
 async function save(e:React.FormEvent){e.preventDefault();setError("");setNotice("");const services=[];
  for(const item of items){const value=item.price.trim().replace(",",".");if(!/^\d{1,4}(\.\d{1,2})?$/.test(value)){setError("Informe os preços como 25 ou 25,50.");return}const priceCents=Math.round(Number(value)*100);if(priceCents<100||priceCents>100000){setError("Informe preços entre R$ 1,00 e R$ 1.000,00.");return}services.push({id:item.id,name:item.name.trim(),priceCents,duration:item.duration})}
  setSaving(true);try{const r=await fetch("/api/services",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({services})}),j:any=await r.json();if(!r.ok)throw Error(j.error);setItems(drafts(j.services));setNotice("Serviços salvos e disponíveis no agendamento.")}catch(e){setError(e instanceof Error?e.message:"Não foi possível salvar.")}finally{setSaving(false)}
 }
 return <section id="servicos" className="service-editor"><h3><Scissors size={20}/>Serviços e preços</h3><p className="muted">Cadastre opções de corte e edite nome, preço e duração. Reservas já feitas mantêm os dados combinados.</p>{loading?<p role="status">Carregando serviços…</p>:items.length?<form onSubmit={save}><fieldset disabled={saving} className="service-editor-fields">{items.map((item,i)=><div className="service-edit-row service-edit-expanded" key={item.id}><label htmlFor={`service-name-${item.id}`}>Nome do serviço {i+1}<input id={`service-name-${item.id}`} value={item.name} onChange={e=>edit(item.id,"name",e.target.value)} minLength={2} maxLength={60} required/></label><label htmlFor={`service-price-${item.id}`}>Preço (R$)<input id={`service-price-${item.id}`} type="text" inputMode="decimal" value={item.price} onChange={e=>edit(item.id,"price",e.target.value)} required/></label><label htmlFor={`service-duration-${item.id}`}>Duração<NativeSelect id={`service-duration-${item.id}`} value={item.duration} onChange={e=>edit(item.id,"duration",Number(e.target.value))}>{[30,60,90,120].map(n=><NativeSelectOption key={n} value={n}>{n} min</NativeSelectOption>)}</NativeSelect></label></div>)}<div className="settings-actions"><button type="button" className="settings-secondary" disabled={items.length>=30} onClick={()=>{setItems(v=>[...v,{id:`svc_${crypto.randomUUID()}`,name:"",price:"",duration:30}]);setNotice("")}}><Plus size={18}/>Adicionar serviço</button><button type="submit" className="primary"><Save size={18}/>{saving?"Salvando…":"Salvar serviços"}</button></div></fieldset></form>:<button type="button" className="primary" onClick={load}>Tentar novamente</button>}{error&&<p className="error" role="alert">{error}</p>}{notice&&<p className="admin-notice" role="status">{notice}</p>}</section>
}
