"use client";
import {useEffect,useState} from "react";
import {Globe,LockKeyhole} from "lucide-react";
import {Switch} from "@/components/ui/switch";
export default function Settings(){
 const [isPublic,setPublic]=useState<boolean|null>(null),[accessBusy,setAccessBusy]=useState(false),[accessError,setAccessError]=useState(""),[accessNotice,setAccessNotice]=useState("");
 const [current,setCurrent]=useState(""),[password,setPassword]=useState(""),[confirm,setConfirm]=useState(""),[saving,setSaving]=useState(false),[error,setError]=useState(""),[notice,setNotice]=useState("");
 async function load(){setAccessError("");try{const r=await fetch("/api/barber-settings",{cache:"no-store"}),j:any=await r.json();if(!r.ok)throw Error(j.error);setPublic(j.isPublic)}catch(e){setAccessError(e instanceof Error?e.message:"Não foi possível carregar o acesso.")}}
 useEffect(()=>{load()},[]);
 async function access(value:boolean){setAccessBusy(true);setAccessError("");setAccessNotice("");try{const r=await fetch("/api/barber-settings",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({isPublic:value})}),j:any=await r.json();if(!r.ok)throw Error(j.error);setPublic(j.isPublic);setAccessNotice(value?"Site aberto ao público.":"Site privado. Somente o barbeiro conectado pode acessar o conteúdo.")}catch(e){setAccessError(e instanceof Error?e.message:"Não foi possível alterar o acesso.")}finally{setAccessBusy(false)}}
 async function changePassword(e:React.FormEvent){e.preventDefault();setError("");setNotice("");if(password!==confirm){setError("A confirmação deve ser igual à nova senha.");return}setSaving(true);try{const r=await fetch("/api/barber-password",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({currentPassword:current,newPassword:password,confirmPassword:confirm})}),j:any=await r.json();if(!r.ok)throw Error(j.error);setCurrent("");setPassword("");setConfirm("");setNotice("Senha alterada. Os outros acessos foram encerrados e você continua conectado.")}catch(e){setError(e instanceof Error?e.message:"Não foi possível alterar a senha.")}finally{setSaving(false)}}
 return <><section id="acesso" className="service-editor"><h3><Globe size={20}/>Acesso ao site</h3><div className="visibility-control"><div><label htmlFor="site-public">{isPublic===null?"Carregando acesso…":isPublic?"Site público":"Site privado"}</label><p className="muted">{isPublic?"Clientes podem ver o site e fazer agendamentos.":"Visitantes veem apenas um aviso de acesso privado. O painel continua disponível pelo login."}</p></div><Switch id="site-public" aria-label="Abrir site ao público" checked={isPublic===true} disabled={isPublic===null||accessBusy} onCheckedChange={access}/></div>{accessBusy&&<p role="status">Alterando acesso…</p>}{accessNotice&&<p role="status" className="admin-notice">{accessNotice}</p>}{accessError&&<div className="error" role="alert">{accessError}{isPublic===null&&<button onClick={load}>Tentar novamente</button>}</div>}</section><section id="senha" className="service-editor"><h3><LockKeyhole size={20}/>Senha de acesso</h3><p className="muted">Use uma nova senha com pelo menos 8 caracteres. O nome de usuário permanece o mesmo.</p><form onSubmit={changePassword}><fieldset className="password-fields" disabled={saving}><label>Senha atual<input type="password" autoComplete="current-password" value={current} onChange={e=>setCurrent(e.target.value)} maxLength={128} required/></label><label>Nova senha<input type="password" autoComplete="new-password" value={password} onChange={e=>setPassword(e.target.value)} minLength={8} maxLength={128} required/></label><label>Confirmar nova senha<input type="password" autoComplete="new-password" value={confirm} onChange={e=>setConfirm(e.target.value)} minLength={8} maxLength={128} required/></label><button type="submit" className="primary">{saving?"Alterando senha…":"Alterar senha"}</button></fieldset></form>{error&&<p className="error" role="alert">{error}</p>}{notice&&<p className="admin-notice" role="status">{notice}</p>}</section></>;
}
